### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by airyland** [iseekr/website-server#1]
- [ ]  add a website (create a database)
- [ ]  remove a website (with confirm)
- [ ]  update website info
